### ISSUE TITLE
Como jugador quiero maná

### ISSUE THREAD

**Issue by LauraWangQiu** [UCM-FDI-DISIA/nullptr#118]
- [x] El maná baja si uso una habilidad
- [x] No poder usar una habilidad si no tengo suficiente maná
- [x] Los enemigos sueltan mana
