### ISSUE TITLE
Como jugador quiero un enemigo tipo tanque

### ISSUE THREAD

**Issue by LauraWangQiu** [UCM-FDI-DISIA/nullptr#12]
- [ ] Como enemigo tanque quiero atacar en un área a mi alrededor
- [ ] Vida (misma que jugador)
- [ ] Lógica de movimiento
