### ISSUE TITLE
Como jugador quiero atacar con la carta seleccionada y gastarle un uso

### ISSUE THREAD

**Issue by LauraWangQiu** [UCM-FDI-DISIA/nullptr#27]
- [x] Ataque base (stat jugador)
- [x] Velocidad de ataque base (stat jugador)
- [x] Usar la carta con cadencia
