### ISSUE TITLE
Como jugador quiero una escena de cofre

### ISSUE THREAD

**Issue by DDiegoP** [UCM-FDI-DISIA/nullptr#360]
- [ ] Como cofre quiero un gacha de objetos
- [ ] Como objetos de cofre quiero distintas probabilidades de salir
- [ ] Como cofre quiero una animación de apertura
- [ ] Como cofre quiero una imagen para insertar en el mapa de nodos
