### ISSUE TITLE
Como jugador quiero una escena de tienda

### ISSUE THREAD

**Issue by DDiegoP** [UCM-FDI-DISIA/nullptr#361]
- [ ] Conseguir que aparezcan cartas de manera aleatoria
- [ ] Poder comprar cartas y que se añadan al inventario
- [ ] Ver el dinero disponible
- [ ] Poder ver las cartas que puedo comprar y su precio
- [ ] Ver la información de cada carta (Hablar con inventTeam)
- [ ] Tener arte de nodo
- [ ] Tener arte de un vendedor de cartas
