### ISSUE TITLE
Como jugador quiero poder enfrentarme al jefe

### ISSUE THREAD

**Issue by DDiegoP** [UCM-FDI-DISIA/nullptr#388]
- [x] El jefe dispara
- [x] Tiene sus patrones definidos
- [x] Usar sus patrones como se refleja en el GDD
- [x] Poder recibir daño
- [x] Poder morir
