### ISSUE TITLE
Como jugador quiero un enemigo tipo tirador

### ISSUE THREAD

**Issue by LauraWangQiu** [UCM-FDI-DISIA/nullptr#44]
- [x] Como enemigo tirador quiero atacar con proyectiles a distancia
- [x] Vida (misma que jugador)
- [x] Lógica de movimiento
