### ISSUE TITLE
Como jugador quiero sonido de enemigo especial

### ISSUE THREAD

**Issue by DDiegoP** [UCM-FDI-DISIA/nullptr#489]
- [ ] Sonido de muerte de enemigo especial
- [ ] Sonido de daño de enemigo especial
- [ ] Sonido de dash de enemigo especial
