### ISSUE TITLE
Como jugador quiero diferenciar los distintos proyectiles del juego

### ISSUE THREAD

**Issue by Rafaa0514** [UCM-FDI-DISIA/nullptr#507]
- [x] Balas normales (pistola, SMG, rifle)
- [x] Balas de luz (blaster)
- [x] Flechas (enemigos y jugador)
- [x] Pulga (bala y explosion)
- [x] Proyectil del jefe (cristal)
- [x] Granadas (jefe y jugador)
- [x] Explosion de luz
- [x] Tentaculo (jefe final)
