### ISSUE TITLE
Como jugador quiero ver una escena post Combate

### ISSUE THREAD

**Issue by MiguelCGa** [UCM-FDI-DISIA/nullptr#86]
- [x] Se debe generar al terminar el combate
- [x] Debe dar una carta nueva correspondiente con el tiempo del combate
- [x] Mostrar el oro obtenido
- [x] Mostrar enemigos derrotados
- [x] Mostrar daño recibido
